node {
   stage('Git checkout') { // for display purposes
      git 'https://github.com/arora-raghav/automation.git'
   }
   stage('Testing') {
        try {
            bat "mvn -f ./com.t-mobile/pom.xml clean test"
        } catch (err) {
            
        } finally {
            publishHTML (target: [
            reportDir: 'target/site/serenity',
            reportFiles: 'index.html',
            reportName: "UI tests report"
            ])
        }
   }
}
